Treino Para Revisão
AllanGBOliveira/Treinamento pull request #1
Opened 2020-09-11 17:25 UTC by AlleYuYo

2020-09-15 13:04 UTC, danilopinotti requested changes

2020-09-15 13:04 UTC, danilopinotti commented on app/Books.php
> +class Books extends Model
Models devem ter o nome no singular.

```suggestion
class Book extends Model
```

2020-09-15 13:04 UTC, danilopinotti commented on app/Http/Controllers/BooksController.php
> +        \App\Books::create($data);
?

2020-09-15 13:04 UTC, danilopinotti commented on app/Http/Controllers/BooksController.php
> +    public function store(Request $request)
Para todo endpoint que salva dados no banco de dados, você deve validar os dados de entrada.
Você pode fazer a validação dos dados no Form Request: https://laravel.com/docs/7.x/validation#form-request-validation

2020-09-15 13:04 UTC, danilopinotti commented on app/Http/Controllers/BooksController.php
> +        unset($data['_token']);
Nõa há necessidade de fazer o 'unset' destes campos, visto que eles não estão no $fillable do model Books

2020-09-15 13:04 UTC, danilopinotti commented on app/Http/Controllers/BooksController.php
> +         \App\Books::where('id',$id)->update($data);
Você pode utilizar o find em vez do where...id.

```suggestion
         \App\Books::find($id)->update($data);
```

2020-09-15 13:04 UTC, danilopinotti commented on app/Http/Controllers/BooksController.php
> +    $data = $request->all();
Corrigir indentação

2020-09-15 13:04 UTC, danilopinotti commented on app/Http/Controllers/BooksController.php
> +  public function val(Request $request,$id)
O nome do método não está descritivo.
O que é val?

2020-09-15 13:04 UTC, danilopinotti commented on resources/views/books.blade.php
> +    a.btn {
É recomendado colocar estilos CSS em arquivos separados e exclusivos para isso (arquivos .css)

2020-09-15 13:04 UTC, danilopinotti commented on resources/views/books.blade.php
> +                                    {{ date('d/m/Y', strtotime($book->created_at)) }}
O created_at retorna um objeto Carbon. Você pode fazer a formatação utilizando os próprios métodos do Carbon.

2020-09-15 13:04 UTC, danilopinotti commented on routes/web.php
> +Route::get('/add', function () {
Evitar declarar rotas em funções anônimas.
Em versões do Laravel inferiores à 8.x, este tipo de declaração gera erros na hora de criar o cache das rotas (php artisan route:cache)

2020-09-15 13:04 UTC, danilopinotti commented on app/Http/Controllers/BooksController.php
> +        $books = \App\Books::where('id',$id)->first();
Você pode utilizar o find.
```suggestion
        $books = \App\Books::find($id);
```

2020-09-15 13:04 UTC, danilopinotti commented on app/Http/Controllers/BooksController.php
> +    public function reserve($id)
Por mais que eu saiba do que se trata esta variável, é uma boa prática sempre deixá-la o mais descritível possível.
```suggestion
    public function reserve($bookId)
```

2020-09-15 13:04 UTC, danilopinotti commented on app/Http/Controllers/BooksController.php
> +        return redirect('/books');
É uma boa prática sempre trabalhar com rotas referenciando-as pelo nome: https://laravel.com/docs/8.x/routing#named-routes

O motivo disso é que a URL pode mudar de acordo com a necessidade (internacionalização do sistema, por exemplo), já o nome da rota é mantido o mesmo internamente.

2020-09-15 13:04 UTC, danilopinotti commented on app/Http/Controllers/BooksController.php
> +        $data = $request->all();
Não há necessidade desta linha e nem das duas logo abaixo

2020-09-15 13:04 UTC, danilopinotti commented on app/Http/Controllers/BooksController.php
> +        $books = \App\Books::where('id',$id)->first();
O nome da variável está no plural, dando a entender que possuem vários livros nesta variável. O código diz que só há um livro.
O nome da variável deveria ser somente $book (singular).

Além disso, você pode utilizar o método find.
```suggestion
        $books = \App\Books::find($id);
```

2020-09-15 13:04 UTC, danilopinotti commented on app/Http/Controllers/BooksController.php
> +        $books = \App\Books::all();
É uma má pratica carregar tudo em memória. Quanto mais livros cadastrados, mais pesado fica pro servidor carregar estas informações e mais pesado fica para o usuário acessar esta tela.

O correto é você paginar ests informações.
O Laravel fornece uma maneira bem simples de fazer isso: https://laravel.com/docs/7.x/pagination#introduction

2020-09-15 13:04 UTC, danilopinotti commented on app/Http/Controllers/BooksController.php
> +    public function show($id)
Evitar subir código não utilizado ou código comentado. A ideia é manter sempre limpo.

2020-09-15 13:14 UTC, pedroida commented
[apontamentos-pedro.txt](https://github.com/AlleYuYo/Treinamento/files/5225069/apontamentos-pedro.txt)

alguns pontos de interface que identifiquei ao fazer os testes de usabilidade

2020-09-15 13:56 UTC, danilopinotti commented
Reparei que sua tarefa tem apenas um único commit. Isso não é uma boa prática.
Recomendo a leitura deste artigo: https://ruanbrandao.com.br/2020/02/04/como-fazer-um-bom-commit/

2020-09-15 13:58 UTC, AlleYuYo commented
Pse eu esqueci q n tava no meu PC aí fui lembrar do git só depois de
terminar kkkk

Em ter, 15 de set de 2020 10:57, Danilo Pinotti <notifications@github.com>
escreveu:

> Reparei que sua tarefa tem apenas um único commit. Isso não é uma boa
> prática.
> Recomendo a leitura deste artigo:
> https://ruanbrandao.com.br/2020/02/04/como-fazer-um-bom-commit/
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/AlleYuYo/Treinamento/pull/1#issuecomment-692732044>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AHY2YRHKSD4NHNEENM4P4PTSF5XDJANCNFSM4RH6IDDA>
> .
>

2020-09-16 11:29 UTC, AlleYuYo commented on app/Http/Controllers/BooksController.php
> +    public function store(Request $request)
Mesmo os dados que não são aletrados manualmente pelo usuário como por exemplo o delete?

2020-09-16 12:49 UTC, AlleYuYo commented on app/Books.php
> +class Books extends Model
Feito

2020-09-16 12:50 UTC, AlleYuYo commented on app/Http/Controllers/BooksController.php
> +        $books = \App\Books::all();
dei o paginate e usei o links() na blade

2020-09-16 12:50 UTC, AlleYuYo commented on app/Http/Controllers/BooksController.php
> +        \App\Books::create($data);
kkk erro meu

2020-09-16 12:50 UTC, AlleYuYo commented on app/Http/Controllers/BooksController.php
> +        unset($data['_token']);
Feito.

2020-09-16 12:51 UTC, AlleYuYo commented on app/Http/Controllers/BooksController.php
> +    public function show($id)
Feito

2020-09-16 12:51 UTC, AlleYuYo commented on app/Http/Controllers/BooksController.php
> +        $books = \App\Books::where('id',$id)->first();
Feito

2020-09-16 12:51 UTC, AlleYuYo commented on app/Http/Controllers/BooksController.php
> +         \App\Books::where('id',$id)->update($data);
vlw nao sabia do find.

2020-09-16 12:52 UTC, AlleYuYo commented on app/Http/Controllers/BooksController.php
> +        $data = $request->all();
feito

2020-09-16 12:52 UTC, AlleYuYo commented on app/Http/Controllers/BooksController.php
> +        return redirect('/books');
ok

2020-09-16 12:53 UTC, AlleYuYo commented on app/Http/Controllers/BooksController.php
> +    public function reserve($id)
feito

2020-09-16 12:53 UTC, AlleYuYo commented on app/Http/Controllers/BooksController.php
> +        $books = \App\Books::where('id',$id)->first();
.

2020-09-16 12:53 UTC, AlleYuYo commented on app/Http/Controllers/BooksController.php
> +  public function val(Request $request,$id)
nossa nem lembrei de trocar kk mas agora está corrigido

2020-09-16 12:53 UTC, AlleYuYo commented on app/Http/Controllers/BooksController.php
> +    $data = $request->all();
feito

2020-09-16 12:54 UTC, AlleYuYo commented on resources/views/books.blade.php
> +    a.btn {
ok

2020-09-16 12:54 UTC, AlleYuYo commented on resources/views/books.blade.php
> +                                    {{ date('d/m/Y', strtotime($book->created_at)) }}
feito

2020-09-16 12:54 UTC, AlleYuYo commented on routes/web.php
> +Route::get('/add', function () {
feito

2020-09-17 17:23 UTC, pedroida commented on app/Http/Controllers/BooksController.php
> +        $book = \App\Book::paginate(5);
Aqui a variável deve ter `$books` já que traz uma paginação de livros

2020-09-17 17:25 UTC, pedroida commented on app/Http/Controllers/BooksController.php
> +        $bookId = Auth::id();
nome não condiz com o valor, já que armazena o Id do usuário corrente, deve se chamar `$userId`

2020-09-17 17:25 UTC, pedroida commented on app/Http/Controllers/BooksController.php
> +        $bookId = Auth::id();
nome da varável não condiz com o valor, deve se chamar `$userId` já que armazena o id de um usuário, não de um livro

2020-09-17 20:35 UTC, AlleYuYo commented on app/Http/Controllers/BooksController.php
> +        $bookId = Auth::id();
feito

2020-09-17 20:35 UTC, AlleYuYo commented on app/Http/Controllers/BooksController.php
> +        $bookId = Auth::id();
feito

2020-09-17 20:36 UTC, AlleYuYo commented on app/Http/Controllers/BooksController.php
> +        $book = \App\Book::paginate(5);
feito

2025-09-02 22:15 UTC, merged